<?php
/**
 * The header for our theme
 *
 * This is the template that displays all of the <head> section and everything up until <div id="content">
 *
 * @link https://developer.wordpress.org/themes/basics/template-files/#template-partials
 *
 * @package And_Also_Too
 */

?><!DOCTYPE html>
<html <?php language_attributes(); ?>>
<head>
<meta charset="<?php bloginfo( 'charset' ); ?>">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="profile" href="http://gmpg.org/xfn/11">
<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Montserrat|Vollkorn|Roboto">
<?php wp_head(); ?>
</head>

<body <?php body_class(); ?>>
<div id="page" class="site">
	<a class="skip-link screen-reader-text" href="#content"><?php esc_html_e( 'Skip to content', 'and-also-too' ); ?></a>

	<header id="masthead" class="site-header" role="banner">
		<div class="header-content">

			<div class="site-branding-medium">
				<?php the_custom_logo(); ?>
			</div><!-- .site-branding -->

			<nav id="site-navigation" class="main-navigation" role="navigation">
				<div class="site-branding">
					<img src="http://and-also-too.dev/wp-content/uploads/2017/02/toggle-logo.png" alt="">
				</div>
				<!--<ul id="primary-menu" class="simple-toggle nav-menu"</ul>  generated by WP -->
				<div class="mobile-nav-middle">
					<?php wp_nav_menu( array( 'theme_location' => 'menu-1', 'menu_id' => 'primary-menu', 'menu_class' => 'simple-toggle', 'container' => 'ul' ) ); ?>

					<div class="nav-social">
						<i class="fa fa-twitter-square" aria-hidden="true"></i>
						<i class="fa fa-facebook-square" aria-hidden="true"></i>
						<i class="fa fa-instagram" aria-hidden="true"></i>
						<i class="fa fa-linkedin-square" aria-hidden="true"></i>
					</div>
				</div>
				<span>
					<a id="close-toggle" class="anchor-close" href="#">
						<i class="fa fa-times" aria-hidden="true"></i> CLOSE
					</a>
				</span>
			</nav><!-- #site-navigation -->
			<span class="anchor-link">
				<a id="open-toggle" href="#">
					<i class="fa fa-bars" aria-hidden="true"></i>
					Menu
				</a>
			</span>
			<div class="nav-social-medium">
				<i class="fa fa-twitter-square" aria-hidden="true"></i>
				<i class="fa fa-facebook-square" aria-hidden="true"></i>
				<i class="fa fa-instagram" aria-hidden="true"></i>
				<i class="fa fa-linkedin-square" aria-hidden="true"></i>
			</div>




		</span><!-- .site-header -->

	</header><!-- #masthead -->

	<div id="content" class="site-content">
